version: "3.8"

services:
  linux:
    build:
      context: .
      dockerfile: src/Dockerfile
      args:
        VERSION: 1.0.1-dev
    image: netlah/spa-host:dev1
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Serilog.AspNetCore.RequestLoggingMiddleware=Debug
      - Serilog__MinimumLevel__Override__Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware=Debug

  windows:
    build:
      context: .
      dockerfile: src/Dockerfile-windows
      args:
        VERSION: 1.0.1-dev
    image: netlah/spa-host:dev1
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__MinimumLevel__Override__Serilog.AspNetCore.RequestLoggingMiddleware=Debug
      - Serilog__MinimumLevel__Override__Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware=Debug
